# Exported from Render on 2026-03-25T20:09:06Z
version: "1"
services:
- type: web
  name: Promptly-v0.6-CloudTest (Cursor-dev)
  runtime: node
  repo: https://github.com/MaxonT/Promptly-v0.6-CloudTest
  branch: cursor-dev
  plan: starter
  envVars:
  - key: OAUTH_REDIRECT_URI
    sync: false
  - key: FRONTEND_URL
    sync: false
  - key: CORS_ORIGIN
    sync: false
  - key: ANTHROPIC_API_KEY
    sync: false
  - key: STRIPE_PRICE_YEARLY
    sync: false
  - key: STRIPE_PRICE_MONTHLY
    sync: false
  - key: SQLITE_PATH
    value: /var/data/app.db
  - key: STRIPE_SECRET_KEY
    sync: false
  - key: STRIPE_PUBLISHABLE_KEY
    sync: false
  - key: STRIPE_WEBHOOK_SECRET
    sync: false
  - key: GOOGLE_CLIENT_SECRET
    sync: false
  - key: GOOGLE_CLIENT_ID
    sync: false
  - key: GITHUB_CLIENT_SECRET
    sync: false
  - key: GITHUB_CLIENT_ID
    sync: false
  - key: OPENAI_BASE_URL
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  - key: NODE_ENV
    value: production
  - key: JWT_SECRET
    generateValue: true
  - key: GROQ_BASE_URL
    sync: false
  - key: GROQ_API_KEY
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm start
  disk:
    name: disk
    mountPath: /var/data
    sizeGB: 1
  autoDeployTrigger: commit
  rootDir: Promptly-cloud-v0.6.8.3-fullstack/backend
  previews:
    generation: automatic
