#!/usr/bin/env node

/**
 * Build script for Promptly Frontend
 * Generates config.js from environment variables
 * 
 * Supported environment variables (in order of priority):
 * 1. VITE_API_BASE
 * 2. PROMPTLY_API_BASE
 * 3. API_BASE
 * 4. Default: http://localhost:8080
 */

const fs = require('fs');
const path = require('path');

// Get API base URL from environment variable
const apiBase = process.env.VITE_API_BASE || 
                process.env.PROMPTLY_API_BASE || 
                process.env.API_BASE ||
                'http://localhost:8080';

// Remove trailing slash if present
const cleanApiBase = apiBase.replace(/\/$/, '');

console.log('========================================');
console.log('[Promptly Build] Generating config.js...');
console.log('========================================');
console.log('Environment variables checked:');
console.log('  VITE_API_BASE:', process.env.VITE_API_BASE || '(not set)');
console.log('  PROMPTLY_API_BASE:', process.env.PROMPTLY_API_BASE || '(not set)');
console.log('  API_BASE:', process.env.API_BASE || '(not set)');
console.log('');
console.log('✅ Using API Base URL:', cleanApiBase);
console.log('✅ Build timestamp:', new Date().toISOString());
console.log('========================================');

// Generate config.js content
const configContent = `// ============================================
// Promptly Frontend - API Configuration
// ============================================
// 
// ⚠️  DO NOT EDIT THIS FILE MANUALLY
// This file is auto-generated during build from environment variables
// 
// To change the API base URL:
// 1. Set environment variable: VITE_API_BASE or PROMPTLY_API_BASE
// 2. Run: npm run build
// 
// Generated at: ${new Date().toISOString()}
// Source: ${process.env.VITE_API_BASE ? 'VITE_API_BASE' : process.env.PROMPTLY_API_BASE ? 'PROMPTLY_API_BASE' : process.env.API_BASE ? 'API_BASE' : 'default'}
// ============================================

window.PROMPTLY_API_BASE = "${cleanApiBase}";

console.log("[Promptly] API Base configured:", window.PROMPTLY_API_BASE);
console.log("[Promptly] Config generated at:", "${new Date().toISOString()}");
console.log("[Promptly] Environment:", "${process.env.NODE_ENV || 'production'}");
`;

// Write to config.js
const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('');
console.log('✅ config.js generated successfully!');
console.log('📁 Location:', configPath);
console.log('📏 Size:', fs.statSync(configPath).size, 'bytes');
console.log('');
console.log('Next steps:');
console.log('1. Deploy to Vercel with VITE_API_BASE environment variable');
console.log('2. Test in browser console: window.PROMPTLY_API_BASE');
console.log('========================================');

