#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
剩余语言翻译脚本 - 阿拉伯语、韩语、葡萄牙语、印地语
基于 en.json 进行专业翻译
"""

import json

# 读取英文翻译作为基准
with open('frontend/locales/en.json', 'r', encoding='utf-8') as f:
    en = json.load(f)

# 阿拉伯语翻译映射
ar_translations = {
    # Common module
    "common": {
        "appName": "Promptly",
        "welcome": "مرحبا",
        "loading": "جار التحميل...",
        "error": "خطأ",
        "success": "نجاح",
        "cancel": "إلغاء",
        "confirm": "تأكيد",
        "save": "حفظ",
        "delete": "حذف",
        "edit": "تعديل",
        "close": "إغلاق",
        "back": "رجوع",
        "next": "التالي",
        "submit": "إرسال",
        "reset": "إعادة تعيين",
        "search": "بحث",
        "filter": "تصفية",
        "sort": "ترتيب",
        "export": "تصدير",
        "import": "استيراد",
        "download": "تنزيل",
        "upload": "رفع",
        "view": "عرض",
        "copy": "نسخ",
        "paste": "لصق",
        "cut": "قص",
        "selectAll": "تحديد الكل",
        "deselectAll": "إلغاء تحديد الكل",
        "refresh": "تحديث",
        "reload": "إعادة تحميل",
        "retry": "إعادة المحاولة",
        "undo": "تراجع",
        "redo": "إعادة",
        "help": "مساعدة",
        "about": "حول",
        "settings": "الإعدادات",
        "logout": "تسجيل خروج",
        "login": "تسجيل دخول"
    },
    
    # Alerts module
    "alerts": {
        "success": "تمت العملية بنجاح!",
        "error": "حدث خطأ",
        "warning": "تحذير",
        "info": "معلومات",
        "confirmDelete": "هل أنت متأكد من الحذف؟",
        "confirmAction": "هل أنت متأكد من المتابعة؟",
        "unsavedChanges": "لديك تغييرات غير محفوظة",
        "saveSuccess": "تم الحفظ بنجاح",
        "saveFailed": "فشل الحفظ",
        "deleteSuccess": "تم الحذف بنجاح",
        "deleteFailed": "فشل الحذف",
        "updateSuccess": "تم التحديث بنجاح",
        "updateFailed": "فشل التحديث",
        "loadFailed": "فشل تحميل البيانات",
        "networkError": "خطأ في الشبكة، يرجى التحقق من اتصالك",
        "invalidInput": "إدخال غير صالح",
        "requiredField": "هذا الحقل مطلوب",
        "invalidFormat": "تنسيق غير صالح",
        "copySuccess": "تم النسخ إلى الحافظة",
        "copyFailed": "فشل النسخ"
    },
    
    # Hero module
    "hero": {
        "title": "قم بتحسين Prompts الخاصة بـ LLM مع Promptly",
        "subtitle": "منصة احترافية لاختبار وتحسين Prompts مدعومة بالذكاء الاصطناعي",
        "description": "اختبر وقارن وحسّن Prompts الخاصة بـ LLM مع سير عمل آلي ومقاييس احترافية",
        "cta": "ابدأ مجانًا",
        "learnMore": "اعرف المزيد",
        "watchDemo": "شاهد العرض التوضيحي",
        "feature1": "اختبار A/B تلقائي",
        "feature2": "مقاييس في الوقت الفعلي",
        "feature3": "دعم نماذج متعددة",
        "feature4": "إدارة الإصدارات",
        "trustedBy": "موثوق به من قبل",
        "companies": "أكثر من 1000 شركة"
    },
    
    # Dynamic module
    "dynamic": {
        "bestPrompt": "أفضل Prompt",
        "testCases": "حالات الاختبار",
        "successRate": "معدل النجاح",
        "avgTokens": "متوسط Tokens",
        "avgLatency": "متوسط زمن الاستجابة",
        "totalRuns": "إجمالي التشغيلات",
        "lastRun": "آخر تشغيل",
        "status": "الحالة",
        "running": "قيد التشغيل",
        "completed": "مكتمل",
        "failed": "فشل",
        "pending": "معلق",
        "cancelled": "ملغى",
        "noData": "لا توجد بيانات متاحة",
        "loadingData": "جار تحميل البيانات...",
        "refreshData": "تحديث البيانات",
        "autoRefresh": "تحديث تلقائي",
        "realtime": "الوقت الفعلي"
    },
    
    # Glossary module
    "glossary": {
        "title": "المسرد",
        "prompt": "Prompt",
        "promptDesc": "تعليمات الإدخال المعطاة لنموذج اللغة",
        "llm": "LLM (نموذج لغة كبير)",
        "llmDesc": "نماذج لغوية كبيرة مثل GPT و Claude وغيرها",
        "token": "Token",
        "tokenDesc": "وحدة النص التي تعالجها LLM",
        "latency": "Latency",
        "latencyDesc": "وقت استجابة النموذج",
        "temperature": "Temperature",
        "temperatureDesc": "التحكم في عشوائية الإخراج (0-2)",
        "maxTokens": "الحد الأقصى للـ Tokens",
        "maxTokensDesc": "الطول الأقصى للاستجابة",
        "topP": "Top P",
        "topPDesc": "أخذ عينات النواة للتنوع",
        "frequencyPenalty": "Frequency Penalty",
        "frequencyPenaltyDesc": "تقليل تكرار الكلمات (-2 إلى 2)",
        "presencePenalty": "Presence Penalty",
        "presencePenaltyDesc": "تشجيع مواضيع جديدة (-2 إلى 2)",
        "stopSequence": "تسلسل الإيقاف",
        "stopSequenceDesc": "إيقاف التوليد عند تسلسلات معينة",
        "systemPrompt": "System Prompt",
        "systemPromptDesc": "تعليمات السياق للنموذج",
        "userPrompt": "User Prompt",
        "userPromptDesc": "استعلام المستخدم",
        "assistantPrompt": "Assistant Prompt",
        "assistantPromptDesc": "استجابة النموذج",
        "fewShot": "Few-Shot",
        "fewShotDesc": "التعلم مع أمثلة قليلة",
        "zeroShot": "Zero-Shot",
        "zeroShotDesc": "التعلم بدون أمثلة",
        "chainOfThought": "Chain of Thought",
        "chainOfThoughtDesc": "التفكير خطوة بخطوة",
        "embedding": "Embedding",
        "embeddingDesc": "التمثيل الشعاعي للنص",
        "vectorDB": "قاعدة بيانات شعاعية",
        "vectorDBDesc": "تخزين للبحث الدلالي",
        "rag": "RAG (التوليد المعزز بالاسترجاع)",
        "ragDesc": "التوليد المعزز بالاسترجاع",
        "fineTuning": "Fine-Tuning",
        "fineTuningDesc": "تدريب نموذج على بيانات محددة",
        "inference": "Inference",
        "inferenceDesc": "توليد الاستجابات بواسطة النموذج"
    },
    
    # Test Cases module
    "testCases": {
        "title": "حالات الاختبار",
        "create": "إنشاء حالة اختبار",
        "edit": "تعديل حالة الاختبار",
        "delete": "حذف حالة الاختبار",
        "run": "تشغيل الاختبار",
        "runAll": "تشغيل الكل",
        "stopAll": "إيقاف الكل",
        "name": "الاسم",
        "description": "الوصف",
        "input": "الإدخال",
        "expectedOutput": "الإخراج المتوقع",
        "actualOutput": "الإخراج الفعلي",
        "result": "النتيجة",
        "passed": "نجح",
        "failed": "فشل",
        "skipped": "متخطى",
        "duration": "المدة",
        "createdAt": "تاريخ الإنشاء",
        "updatedAt": "تاريخ التحديث",
        "lastRun": "آخر تشغيل",
        "runCount": "عدد التشغيلات",
        "successRate": "معدل النجاح",
        "avgDuration": "متوسط المدة",
        "tags": "الوسوم",
        "priority": "الأولوية",
        "high": "عالية",
        "medium": "متوسطة",
        "low": "منخفضة",
        "category": "الفئة",
        "functional": "وظيفي",
        "performance": "الأداء",
        "security": "الأمان",
        "usability": "سهولة الاستخدام",
        "compatibility": "التوافق",
        "regression": "التراجع",
        "smoke": "الدخان",
        "integration": "التكامل",
        "unit": "الوحدة",
        "e2e": "من البداية للنهاية"
    },
    
    # User Guide module
    "userGuide": {
        "title": "دليل المستخدم",
        "welcome": "مرحبًا بك في Promptly",
        "gettingStarted": "البدء",
        "quickStart": "البداية السريعة",
        "tutorial": "البرنامج التعليمي",
        "documentation": "التوثيق",
        "faq": "الأسئلة الشائعة",
        "support": "الدعم",
        "contact": "اتصل بنا",
        "feedback": "ملاحظات",
        "reportBug": "الإبلاغ عن خطأ",
        "featureRequest": "طلب ميزة",
        "step1": "الخطوة 1: إنشاء مشروع",
        "step1Desc": "ابدأ بإنشاء مشروع جديد لتنظيم Prompts الخاصة بك",
        "step2": "الخطوة 2: إضافة Prompts",
        "step2Desc": "أضف Prompts الخاصة بك وقم بتكوين المعلمات",
        "step3": "الخطوة 3: تشغيل الاختبارات",
        "step3Desc": "قم بتشغيل الاختبارات وتحليل النتائج",
        "step4": "الخطوة 4: التحسين",
        "step4Desc": "استخدم الرؤى لتحسين Prompts الخاصة بك",
        "tips": "نصائح",
        "tip1": "استخدم System Prompts واضحة وموجزة",
        "tip2": "اختبر عدة متغيرات للعثور على الأفضل",
        "tip3": "راقب مقاييس الأداء",
        "tip4": "كرر بناءً على النتائج",
        "bestPractices": "أفضل الممارسات",
        "practice1": "حدد معايير نجاح واضحة",
        "practice2": "استخدم حالات اختبار متنوعة",
        "practice3": "قم بإدارة إصدارات Prompts الخاصة بك",
        "practice4": "وثّق قراراتك",
        "troubleshooting": "استكشاف الأخطاء وإصلاحها",
        "issue1": "النموذج لا يستجيب",
        "solution1": "تحقق من اتصال API وحدود المعدل",
        "issue2": "نتائج غير متسقة",
        "solution2": "اضبط Temperature وأضف المزيد من السياق",
        "issue3": "استجابات بطيئة",
        "solution3": "قم بتحسين طول Prompt والحد الأقصى للـ Tokens"
    },
    
    # Layer 1 module
    "layer1": {
        "title": "الطبقة 1: التكوين الأساسي",
        "model": "النموذج",
        "selectModel": "اختر النموذج",
        "modelVersion": "إصدار النموذج",
        "apiKey": "مفتاح API",
        "apiEndpoint": "نقطة نهاية API",
        "temperature": "Temperature",
        "maxTokens": "الحد الأقصى للـ Tokens",
        "topP": "Top P",
        "frequencyPenalty": "Frequency Penalty",
        "presencePenalty": "Presence Penalty",
        "stopSequence": "تسلسل الإيقاف",
        "timeout": "المهلة",
        "retries": "المحاولات",
        "systemPrompt": "System Prompt",
        "systemPromptPlaceholder": "أدخل System Prompt الخاص بك...",
        "advanced": "الإعدادات المتقدمة",
        "basic": "الإعدادات الأساسية",
        "custom": "تكوين مخصص",
        "preset": "الإعدادات المسبقة",
        "creative": "إبداعي",
        "balanced": "متوازن",
        "precise": "دقيق",
        "save": "حفظ التكوين",
        "load": "تحميل التكوين",
        "reset": "إعادة تعيين الافتراضي",
        "validate": "التحقق من التكوين",
        "test": "اختبار التكوين"
    },
    
    # Layer 2 module
    "layer2": {
        "title": "الطبقة 2: الاختبار والتقييم",
        "testSuite": "مجموعة الاختبار",
        "createTest": "إنشاء اختبار",
        "editTest": "تعديل الاختبار",
        "deleteTest": "حذف الاختبار",
        "runTest": "تشغيل الاختبار",
        "runBatch": "تشغيل دفعة",
        "schedule": "جدولة",
        "results": "النتائج",
        "metrics": "المقاييس",
        "comparison": "المقارنة",
        "baseline": "الأساس",
        "variant": "المتغير",
        "winner": "الفائز",
        "confidence": "الثقة",
        "significance": "الأهمية",
        "sampleSize": "حجم العينة",
        "iterations": "التكرارات",
        "concurrency": "التزامن",
        "rateLimit": "حد المعدل",
        "costEstimate": "تقدير التكلفة",
        "timeEstimate": "تقدير الوقت",
        "progress": "التقدم",
        "queue": "الطابور",
        "logs": "السجلات",
        "errors": "الأخطاء",
        "warnings": "التحذيرات",
        "export": "تصدير النتائج",
        "share": "مشاركة النتائج",
        "report": "إنشاء تقرير"
    },
    
    # Layer 3 module
    "layer3": {
        "title": "الطبقة 3: التحسين والنشر",
        "optimize": "تحسين",
        "autoTune": "ضبط تلقائي",
        "suggestions": "الاقتراحات",
        "improvements": "التحسينات",
        "performance": "الأداء",
        "cost": "التكلفة",
        "quality": "الجودة",
        "speed": "السرعة",
        "accuracy": "الدقة",
        "tradeoffs": "المقايضات",
        "deploy": "نشر",
        "version": "الإصدار",
        "changelog": "سجل التغييرات",
        "rollback": "التراجع",
        "monitor": "المراقبة",
        "alerts": "التنبيهات",
        "threshold": "العتبة",
        "notification": "الإخطار",
        "email": "البريد الإلكتروني",
        "webhook": "Webhook",
        "slack": "Slack",
        "dashboard": "لوحة التحكم",
        "analytics": "التحليلات",
        "insights": "الرؤى",
        "trends": "الاتجاهات",
        "forecasts": "التوقعات",
        "recommendations": "التوصيات"
    },
    
    # Pipeline module
    "pipeline": {
        "title": "سير عمل Pipeline",
        "create": "إنشاء Pipeline",
        "edit": "تعديل Pipeline",
        "delete": "حذف Pipeline",
        "run": "تشغيل Pipeline",
        "stop": "إيقاف Pipeline",
        "pause": "إيقاف مؤقت",
        "resume": "استئناف",
        "status": "الحالة",
        "stages": "المراحل",
        "addStage": "إضافة مرحلة",
        "removeStage": "إزالة مرحلة",
        "configure": "تكوين",
        "dependencies": "التبعيات",
        "parallel": "متوازي",
        "sequential": "تسلسلي",
        "conditional": "شرطي",
        "trigger": "المشغل",
        "manual": "يدوي",
        "scheduled": "مجدول",
        "automatic": "تلقائي",
        "webhook": "Webhook"
    },
    
    # WhyPromptly module
    "whyPromptly": {
        "title": "لماذا تختار Promptly؟",
        "subtitle": "المنصة المثالية لتحسين Prompts الـ LLM",
        "reason1Title": "توفير الوقت",
        "reason1Desc": "أتمتة اختبار وتحسين Prompts الخاصة بك",
        "reason2Title": "تقليل التكاليف",
        "reason2Desc": "تحسين استخدام Tokens وتقليل تكاليف API",
        "reason3Title": "جودة محسّنة",
        "reason3Desc": "احصل على نتائج متسقة وعالية الجودة",
        "reason4Title": "رؤى قائمة على البيانات",
        "reason4Desc": "اتخذ قرارات مستنيرة بمقاييس تفصيلية",
        "reason5Title": "سهل الاستخدام",
        "reason5Desc": "واجهة سهلة لجميع مستويات المهارة",
        "reason6Title": "دعم المؤسسات",
        "reason6Desc": "دعم مخصص وميزات المؤسسات",
        "cta": "ابدأ اليوم",
        "testimonial1": "Promptly حوّل سير عمل LLM الخاص بنا",
        "testimonial2": "توفير مذهل في التكاليف وجودة أفضل بكثير",
        "testimonial3": "أفضل أداة لتطوير Prompts",
        "stats1": "أسرع 10 مرات",
        "stats2": "تخفيض 50% في التكاليف",
        "stats3": "99.9% وقت التشغيل",
        "stats4": "أكثر من 1000 مستخدم راضٍ"
    }
}

# 韩语翻译映射
ko_translations = {
    # Common module
    "common": {
        "appName": "Promptly",
        "welcome": "환영합니다",
        "loading": "로딩 중...",
        "error": "오류",
        "success": "성공",
        "cancel": "취소",
        "confirm": "확인",
        "save": "저장",
        "delete": "삭제",
        "edit": "편집",
        "close": "닫기",
        "back": "뒤로",
        "next": "다음",
        "submit": "제출",
        "reset": "재설정",
        "search": "검색",
        "filter": "필터",
        "sort": "정렬",
        "export": "내보내기",
        "import": "가져오기",
        "download": "다운로드",
        "upload": "업로드",
        "view": "보기",
        "copy": "복사",
        "paste": "붙여넣기",
        "cut": "잘라내기",
        "selectAll": "모두 선택",
        "deselectAll": "모두 선택 해제",
        "refresh": "새로 고침",
        "reload": "다시 로드",
        "retry": "재시도",
        "undo": "실행 취소",
        "redo": "다시 실행",
        "help": "도움말",
        "about": "정보",
        "settings": "설정",
        "logout": "로그아웃",
        "login": "로그인"
    },
    
    # Alerts module
    "alerts": {
        "success": "작업이 성공적으로 완료되었습니다!",
        "error": "오류가 발생했습니다",
        "warning": "경고",
        "info": "정보",
        "confirmDelete": "정말 삭제하시겠습니까?",
        "confirmAction": "계속하시겠습니까?",
        "unsavedChanges": "저장되지 않은 변경사항이 있습니다",
        "saveSuccess": "저장에 성공했습니다",
        "saveFailed": "저장에 실패했습니다",
        "deleteSuccess": "삭제에 성공했습니다",
        "deleteFailed": "삭제에 실패했습니다",
        "updateSuccess": "업데이트에 성공했습니다",
        "updateFailed": "업데이트에 실패했습니다",
        "loadFailed": "데이터 로드에 실패했습니다",
        "networkError": "네트워크 오류입니다. 연결을 확인하세요",
        "invalidInput": "유효하지 않은 입력입니다",
        "requiredField": "이 필드는 필수입니다",
        "invalidFormat": "유효하지 않은 형식입니다",
        "copySuccess": "클립보드에 복사되었습니다",
        "copyFailed": "복사에 실패했습니다"
    },
    
    # Hero module
    "hero": {
        "title": "Promptly로 LLM 프롬프트 최적화",
        "subtitle": "AI 기반 전문 프롬프트 테스트 및 최적화 플랫폼",
        "description": "자동화된 워크플로우와 전문 메트릭으로 LLM 프롬프트를 테스트, 비교, 최적화하세요",
        "cta": "무료로 시작하기",
        "learnMore": "자세히 알아보기",
        "watchDemo": "데모 보기",
        "feature1": "자동 A/B 테스트",
        "feature2": "실시간 메트릭",
        "feature3": "멀티 모델 지원",
        "feature4": "버전 관리",
        "trustedBy": "신뢰하는 기업",
        "companies": "1000개 이상의 기업"
    },
    
    # Dynamic module
    "dynamic": {
        "bestPrompt": "최고의 프롬프트",
        "testCases": "테스트 케이스",
        "successRate": "성공률",
        "avgTokens": "평균 토큰",
        "avgLatency": "평균 레이턴시",
        "totalRuns": "총 실행 횟수",
        "lastRun": "마지막 실행",
        "status": "상태",
        "running": "실행 중",
        "completed": "완료",
        "failed": "실패",
        "pending": "대기 중",
        "cancelled": "취소됨",
        "noData": "사용 가능한 데이터가 없습니다",
        "loadingData": "데이터를 불러오는 중...",
        "refreshData": "데이터 새로고침",
        "autoRefresh": "자동 새로고침",
        "realtime": "실시간"
    },
    
    # Glossary module
    "glossary": {
        "title": "용어집",
        "prompt": "프롬프트",
        "promptDesc": "언어 모델에 제공되는 입력 지침",
        "llm": "LLM (대규모 언어 모델)",
        "llmDesc": "GPT, Claude 등과 같은 대규모 언어 모델",
        "token": "토큰",
        "tokenDesc": "LLM이 처리하는 텍스트 단위",
        "latency": "레이턴시",
        "latencyDesc": "모델의 응답 시간",
        "temperature": "Temperature",
        "temperatureDesc": "출력의 무작위성 제어 (0-2)",
        "maxTokens": "최대 토큰",
        "maxTokensDesc": "응답의 최대 길이",
        "topP": "Top P",
        "topPDesc": "다양성을 위한 핵 샘플링",
        "frequencyPenalty": "Frequency Penalty",
        "frequencyPenaltyDesc": "단어 반복 감소 (-2 ~ 2)",
        "presencePenalty": "Presence Penalty",
        "presencePenaltyDesc": "새로운 주제 장려 (-2 ~ 2)",
        "stopSequence": "중지 시퀀스",
        "stopSequenceDesc": "특정 시퀀스에서 생성 중지",
        "systemPrompt": "시스템 프롬프트",
        "systemPromptDesc": "모델의 컨텍스트 지침",
        "userPrompt": "사용자 프롬프트",
        "userPromptDesc": "사용자의 쿼리",
        "assistantPrompt": "어시스턴트 프롬프트",
        "assistantPromptDesc": "모델의 응답",
        "fewShot": "Few-Shot",
        "fewShotDesc": "소수의 예제로 학습",
        "zeroShot": "Zero-Shot",
        "zeroShotDesc": "예제 없이 학습",
        "chainOfThought": "Chain of Thought",
        "chainOfThoughtDesc": "단계별 추론",
        "embedding": "임베딩",
        "embeddingDesc": "텍스트의 벡터 표현",
        "vectorDB": "벡터 데이터베이스",
        "vectorDBDesc": "의미론적 검색을 위한 저장소",
        "rag": "RAG (검색 증강 생성)",
        "ragDesc": "검색으로 증강된 생성",
        "fineTuning": "파인튜닝",
        "fineTuningDesc": "특정 데이터로 모델 훈련",
        "inference": "추론",
        "inferenceDesc": "모델의 응답 생성"
    },
    
    # Test Cases module
    "testCases": {
        "title": "테스트 케이스",
        "create": "테스트 케이스 생성",
        "edit": "테스트 케이스 편집",
        "delete": "테스트 케이스 삭제",
        "run": "테스트 실행",
        "runAll": "모두 실행",
        "stopAll": "모두 중지",
        "name": "이름",
        "description": "설명",
        "input": "입력",
        "expectedOutput": "예상 출력",
        "actualOutput": "실제 출력",
        "result": "결과",
        "passed": "성공",
        "failed": "실패",
        "skipped": "건너뜀",
        "duration": "소요 시간",
        "createdAt": "생성일",
        "updatedAt": "수정일",
        "lastRun": "마지막 실행",
        "runCount": "실행 횟수",
        "successRate": "성공률",
        "avgDuration": "평균 소요 시간",
        "tags": "태그",
        "priority": "우선순위",
        "high": "높음",
        "medium": "중간",
        "low": "낮음",
        "category": "카테고리",
        "functional": "기능",
        "performance": "성능",
        "security": "보안",
        "usability": "사용성",
        "compatibility": "호환성",
        "regression": "회귀",
        "smoke": "스모크",
        "integration": "통합",
        "unit": "단위",
        "e2e": "종단 간"
    },
    
    # User Guide module
    "userGuide": {
        "title": "사용자 가이드",
        "welcome": "Promptly에 오신 것을 환영합니다",
        "gettingStarted": "시작하기",
        "quickStart": "빠른 시작",
        "tutorial": "튜토리얼",
        "documentation": "문서",
        "faq": "자주 묻는 질문",
        "support": "지원",
        "contact": "문의",
        "feedback": "피드백",
        "reportBug": "버그 보고",
        "featureRequest": "기능 요청",
        "step1": "1단계: 프로젝트 생성",
        "step1Desc": "프롬프트를 정리할 새 프로젝트를 만드세요",
        "step2": "2단계: 프롬프트 추가",
        "step2Desc": "프롬프트를 추가하고 매개변수를 설정하세요",
        "step3": "3단계: 테스트 실행",
        "step3Desc": "테스트를 실행하고 결과를 분석하세요",
        "step4": "4단계: 최적화",
        "step4Desc": "인사이트를 사용하여 프롬프트를 최적화하세요",
        "tips": "팁",
        "tip1": "명확하고 간결한 시스템 프롬프트 사용",
        "tip2": "여러 변형을 테스트하여 최고를 찾으세요",
        "tip3": "성능 메트릭 모니터링",
        "tip4": "결과를 바탕으로 반복",
        "bestPractices": "모범 사례",
        "practice1": "명확한 성공 기준 정의",
        "practice2": "다양한 테스트 케이스 사용",
        "practice3": "프롬프트 버전 관리",
        "practice4": "결정 사항 문서화",
        "troubleshooting": "문제 해결",
        "issue1": "모델이 응답하지 않음",
        "solution1": "API 연결 및 속도 제한 확인",
        "issue2": "일관성 없는 결과",
        "solution2": "Temperature를 조정하고 더 많은 컨텍스트 추가",
        "issue3": "느린 응답",
        "solution3": "프롬프트 길이와 최대 토큰 최적화"
    },
    
    # Layer 1 module
    "layer1": {
        "title": "레이어 1: 기본 구성",
        "model": "모델",
        "selectModel": "모델 선택",
        "modelVersion": "모델 버전",
        "apiKey": "API 키",
        "apiEndpoint": "API 엔드포인트",
        "temperature": "Temperature",
        "maxTokens": "최대 토큰",
        "topP": "Top P",
        "frequencyPenalty": "Frequency Penalty",
        "presencePenalty": "Presence Penalty",
        "stopSequence": "중지 시퀀스",
        "timeout": "타임아웃",
        "retries": "재시도",
        "systemPrompt": "시스템 프롬프트",
        "systemPromptPlaceholder": "시스템 프롬프트를 입력하세요...",
        "advanced": "고급 설정",
        "basic": "기본 설정",
        "custom": "사용자 정의 구성",
        "preset": "프리셋",
        "creative": "창의적",
        "balanced": "균형",
        "precise": "정밀",
        "save": "구성 저장",
        "load": "구성 불러오기",
        "reset": "기본값으로 재설정",
        "validate": "구성 검증",
        "test": "구성 테스트"
    },
    
    # Layer 2 module
    "layer2": {
        "title": "레이어 2: 테스트 및 평가",
        "testSuite": "테스트 스위트",
        "createTest": "테스트 생성",
        "editTest": "테스트 편집",
        "deleteTest": "테스트 삭제",
        "runTest": "테스트 실행",
        "runBatch": "일괄 실행",
        "schedule": "일정",
        "results": "결과",
        "metrics": "메트릭",
        "comparison": "비교",
        "baseline": "기준",
        "variant": "변형",
        "winner": "우승자",
        "confidence": "신뢰도",
        "significance": "유의성",
        "sampleSize": "샘플 크기",
        "iterations": "반복",
        "concurrency": "동시성",
        "rateLimit": "속도 제한",
        "costEstimate": "비용 추정",
        "timeEstimate": "시간 추정",
        "progress": "진행률",
        "queue": "대기열",
        "logs": "로그",
        "errors": "오류",
        "warnings": "경고",
        "export": "결과 내보내기",
        "share": "결과 공유",
        "report": "보고서 생성"
    },
    
    # Layer 3 module
    "layer3": {
        "title": "레이어 3: 최적화 및 배포",
        "optimize": "최적화",
        "autoTune": "자동 조정",
        "suggestions": "제안",
        "improvements": "개선 사항",
        "performance": "성능",
        "cost": "비용",
        "quality": "품질",
        "speed": "속도",
        "accuracy": "정확도",
        "tradeoffs": "트레이드오프",
        "deploy": "배포",
        "version": "버전",
        "changelog": "변경 로그",
        "rollback": "롤백",
        "monitor": "모니터",
        "alerts": "알림",
        "threshold": "임계값",
        "notification": "알림",
        "email": "이메일",
        "webhook": "Webhook",
        "slack": "Slack",
        "dashboard": "대시보드",
        "analytics": "분석",
        "insights": "인사이트",
        "trends": "트렌드",
        "forecasts": "예측",
        "recommendations": "권장 사항"
    },
    
    # Pipeline module
    "pipeline": {
        "title": "파이프라인 워크플로우",
        "create": "파이프라인 생성",
        "edit": "파이프라인 편집",
        "delete": "파이프라인 삭제",
        "run": "파이프라인 실행",
        "stop": "파이프라인 중지",
        "pause": "일시정지",
        "resume": "재개",
        "status": "상태",
        "stages": "단계",
        "addStage": "단계 추가",
        "removeStage": "단계 제거",
        "configure": "구성",
        "dependencies": "종속성",
        "parallel": "병렬",
        "sequential": "순차",
        "conditional": "조건부",
        "trigger": "트리거",
        "manual": "수동",
        "scheduled": "예정됨",
        "automatic": "자동",
        "webhook": "Webhook"
    },
    
    # WhyPromptly module
    "whyPromptly": {
        "title": "Promptly를 선택하는 이유",
        "subtitle": "LLM 프롬프트 최적화를 위한 최고의 플랫폼",
        "reason1Title": "시간 절약",
        "reason1Desc": "프롬프트 테스트 및 최적화 자동화",
        "reason2Title": "비용 절감",
        "reason2Desc": "토큰 사용 최적화 및 API 비용 절감",
        "reason3Title": "향상된 품질",
        "reason3Desc": "일관되고 고품질의 결과 제공",
        "reason4Title": "데이터 기반 인사이트",
        "reason4Desc": "상세한 메트릭으로 정보에 입각한 결정",
        "reason5Title": "사용하기 쉬움",
        "reason5Desc": "모든 기술 수준을 위한 직관적인 인터페이스",
        "reason6Title": "엔터프라이즈 지원",
        "reason6Desc": "전담 지원 및 엔터프라이즈 기능",
        "cta": "지금 시작하기",
        "testimonial1": "Promptly가 우리의 LLM 워크플로우를 변화시켰습니다",
        "testimonial2": "놀라운 비용 절감과 훨씬 더 나은 품질",
        "testimonial3": "프롬프트 개발을 위한 최고의 도구",
        "stats1": "10배 더 빠름",
        "stats2": "50% 비용 절감",
        "stats3": "99.9% 가동 시간",
        "stats4": "1000명 이상의 만족한 사용자"
    }
}

# 葡萄牙语翻译映射（使用与法语相同的模块结构）
pt_translations = {
    # Common module
    "common": {
        "appName": "Promptly",
        "welcome": "Bem-vindo",
        "loading": "Carregando...",
        "error": "Erro",
        "success": "Sucesso",
        "cancel": "Cancelar",
        "confirm": "Confirmar",
        "save": "Salvar",
        "delete": "Excluir",
        "edit": "Editar",
        "close": "Fechar",
        "back": "Voltar",
        "next": "Próximo",
        "submit": "Enviar",
        "reset": "Redefinir",
        "search": "Pesquisar",
        "filter": "Filtrar",
        "sort": "Ordenar",
        "export": "Exportar",
        "import": "Importar",
        "download": "Baixar",
        "upload": "Enviar",
        "view": "Ver",
        "copy": "Copiar",
        "paste": "Colar",
        "cut": "Recortar",
        "selectAll": "Selecionar Tudo",
        "deselectAll": "Desmarcar Tudo",
        "refresh": "Atualizar",
        "reload": "Recarregar",
        "retry": "Tentar Novamente",
        "undo": "Desfazer",
        "redo": "Refazer",
        "help": "Ajuda",
        "about": "Sobre",
        "settings": "Configurações",
        "logout": "Sair",
        "login": "Entrar"
    },
    
    # Alerts module
    "alerts": {
        "success": "Operação bem-sucedida!",
        "error": "Ocorreu um erro",
        "warning": "Aviso",
        "info": "Informação",
        "confirmDelete": "Tem certeza de que deseja excluir?",
        "confirmAction": "Tem certeza de que deseja continuar?",
        "unsavedChanges": "Você tem alterações não salvas",
        "saveSuccess": "Salvo com sucesso",
        "saveFailed": "Falha ao salvar",
        "deleteSuccess": "Excluído com sucesso",
        "deleteFailed": "Falha ao excluir",
        "updateSuccess": "Atualizado com sucesso",
        "updateFailed": "Falha ao atualizar",
        "loadFailed": "Falha ao carregar dados",
        "networkError": "Erro de rede, verifique sua conexão",
        "invalidInput": "Entrada inválida",
        "requiredField": "Este campo é obrigatório",
        "invalidFormat": "Formato inválido",
        "copySuccess": "Copiado para a área de transferência",
        "copyFailed": "Falha ao copiar"
    },
    
    # Hero module
    "hero": {
        "title": "Otimize seus Prompts LLM com Promptly",
        "subtitle": "Plataforma profissional de teste e otimização de prompts alimentada por IA",
        "description": "Teste, compare e otimize seus prompts LLM com fluxos de trabalho automatizados e métricas profissionais",
        "cta": "Começar Gratuitamente",
        "learnMore": "Saiba Mais",
        "watchDemo": "Assistir Demo",
        "feature1": "Testes A/B Automatizados",
        "feature2": "Métricas em Tempo Real",
        "feature3": "Suporte Multi-Modelo",
        "feature4": "Gerenciamento de Versão",
        "trustedBy": "Confiado por",
        "companies": "Mais de 1000 empresas"
    },
    
    # Dynamic module
    "dynamic": {
        "bestPrompt": "Melhor Prompt",
        "testCases": "Casos de Teste",
        "successRate": "Taxa de Sucesso",
        "avgTokens": "Tokens Médios",
        "avgLatency": "Latência Média",
        "totalRuns": "Execuções Totais",
        "lastRun": "Última Execução",
        "status": "Status",
        "running": "Em execução",
        "completed": "Concluído",
        "failed": "Falhou",
        "pending": "Pendente",
        "cancelled": "Cancelado",
        "noData": "Nenhum dado disponível",
        "loadingData": "Carregando dados...",
        "refreshData": "Atualizar dados",
        "autoRefresh": "Atualização automática",
        "realtime": "Tempo real"
    },
    
    # Glossary module
    "glossary": {
        "title": "Glossário",
        "prompt": "Prompt",
        "promptDesc": "Instrução de entrada dada a um modelo de linguagem",
        "llm": "LLM (Modelo de Linguagem Grande)",
        "llmDesc": "Modelos de linguagem grandes como GPT, Claude, etc.",
        "token": "Token",
        "tokenDesc": "Unidade de texto processada por LLMs",
        "latency": "Latência",
        "latencyDesc": "Tempo de resposta do modelo",
        "temperature": "Temperature",
        "temperatureDesc": "Controla a aleatoriedade da saída (0-2)",
        "maxTokens": "Tokens Máximos",
        "maxTokensDesc": "Comprimento máximo da resposta",
        "topP": "Top P",
        "topPDesc": "Amostragem de núcleo para diversidade",
        "frequencyPenalty": "Penalidade de Frequência",
        "frequencyPenaltyDesc": "Reduz a repetição de palavras (-2 a 2)",
        "presencePenalty": "Penalidade de Presença",
        "presencePenaltyDesc": "Incentiva novos tópicos (-2 a 2)",
        "stopSequence": "Sequência de Parada",
        "stopSequenceDesc": "Para a geração em sequências específicas",
        "systemPrompt": "Prompt do Sistema",
        "systemPromptDesc": "Instruções de contexto para o modelo",
        "userPrompt": "Prompt do Usuário",
        "userPromptDesc": "Consulta do usuário",
        "assistantPrompt": "Prompt do Assistente",
        "assistantPromptDesc": "Resposta do modelo",
        "fewShot": "Few-Shot",
        "fewShotDesc": "Aprendizado com poucos exemplos",
        "zeroShot": "Zero-Shot",
        "zeroShotDesc": "Aprendizado sem exemplos",
        "chainOfThought": "Cadeia de Pensamento",
        "chainOfThoughtDesc": "Raciocínio passo a passo",
        "embedding": "Embedding",
        "embeddingDesc": "Representação vetorial de texto",
        "vectorDB": "Banco de Dados Vetorial",
        "vectorDBDesc": "Armazenamento para busca semântica",
        "rag": "RAG (Geração Aumentada por Recuperação)",
        "ragDesc": "Geração aumentada por recuperação",
        "fineTuning": "Fine-Tuning",
        "fineTuningDesc": "Treinamento de modelo em dados específicos",
        "inference": "Inferência",
        "inferenceDesc": "Geração de respostas pelo modelo"
    },
    
    # Test Cases module
    "testCases": {
        "title": "Casos de Teste",
        "create": "Criar Caso de Teste",
        "edit": "Editar Caso de Teste",
        "delete": "Excluir Caso de Teste",
        "run": "Executar Teste",
        "runAll": "Executar Todos",
        "stopAll": "Parar Todos",
        "name": "Nome",
        "description": "Descrição",
        "input": "Entrada",
        "expectedOutput": "Saída Esperada",
        "actualOutput": "Saída Real",
        "result": "Resultado",
        "passed": "Passou",
        "failed": "Falhou",
        "skipped": "Ignorado",
        "duration": "Duração",
        "createdAt": "Criado em",
        "updatedAt": "Atualizado em",
        "lastRun": "Última Execução",
        "runCount": "Contagem de Execuções",
        "successRate": "Taxa de Sucesso",
        "avgDuration": "Duração Média",
        "tags": "Tags",
        "priority": "Prioridade",
        "high": "Alta",
        "medium": "Média",
        "low": "Baixa",
        "category": "Categoria",
        "functional": "Funcional",
        "performance": "Desempenho",
        "security": "Segurança",
        "usability": "Usabilidade",
        "compatibility": "Compatibilidade",
        "regression": "Regressão",
        "smoke": "Smoke",
        "integration": "Integração",
        "unit": "Unitário",
        "e2e": "Ponta a Ponta"
    },
    
    # User Guide module
    "userGuide": {
        "title": "Guia do Usuário",
        "welcome": "Bem-vindo ao Promptly",
        "gettingStarted": "Começando",
        "quickStart": "Início Rápido",
        "tutorial": "Tutorial",
        "documentation": "Documentação",
        "faq": "FAQ",
        "support": "Suporte",
        "contact": "Contato",
        "feedback": "Feedback",
        "reportBug": "Reportar Bug",
        "featureRequest": "Solicitar Recurso",
        "step1": "Passo 1: Criar um Projeto",
        "step1Desc": "Comece criando um novo projeto para organizar seus prompts",
        "step2": "Passo 2: Adicionar Prompts",
        "step2Desc": "Adicione seus prompts e configure os parâmetros",
        "step3": "Passo 3: Executar Testes",
        "step3Desc": "Execute seus testes e analise os resultados",
        "step4": "Passo 4: Otimizar",
        "step4Desc": "Use insights para otimizar seus prompts",
        "tips": "Dicas",
        "tip1": "Use prompts de sistema claros e concisos",
        "tip2": "Teste várias variantes para encontrar a melhor",
        "tip3": "Monitore métricas de desempenho",
        "tip4": "Itere com base nos resultados",
        "bestPractices": "Melhores Práticas",
        "practice1": "Defina critérios de sucesso claros",
        "practice2": "Use casos de teste diversos",
        "practice3": "Versione seus prompts",
        "practice4": "Documente suas decisões",
        "troubleshooting": "Solução de Problemas",
        "issue1": "O modelo não responde",
        "solution1": "Verifique sua conexão API e limites de taxa",
        "issue2": "Resultados inconsistentes",
        "solution2": "Ajuste a temperature e adicione mais contexto",
        "issue3": "Respostas lentas",
        "solution3": "Otimize o comprimento do prompt e tokens máximos"
    },
    
    # Layer 1 module
    "layer1": {
        "title": "Camada 1: Configuração Básica",
        "model": "Modelo",
        "selectModel": "Selecionar Modelo",
        "modelVersion": "Versão do Modelo",
        "apiKey": "Chave API",
        "apiEndpoint": "Endpoint da API",
        "temperature": "Temperature",
        "maxTokens": "Tokens Máximos",
        "topP": "Top P",
        "frequencyPenalty": "Penalidade de Frequência",
        "presencePenalty": "Penalidade de Presença",
        "stopSequence": "Sequência de Parada",
        "timeout": "Tempo Limite",
        "retries": "Tentativas",
        "systemPrompt": "Prompt do Sistema",
        "systemPromptPlaceholder": "Digite seu prompt do sistema...",
        "advanced": "Configurações Avançadas",
        "basic": "Configurações Básicas",
        "custom": "Configuração Personalizada",
        "preset": "Predefinições",
        "creative": "Criativo",
        "balanced": "Equilibrado",
        "precise": "Preciso",
        "save": "Salvar Configuração",
        "load": "Carregar Configuração",
        "reset": "Redefinir para Padrão",
        "validate": "Validar Configuração",
        "test": "Testar Configuração"
    },
    
    # Layer 2 module
    "layer2": {
        "title": "Camada 2: Teste e Avaliação",
        "testSuite": "Suíte de Testes",
        "createTest": "Criar Teste",
        "editTest": "Editar Teste",
        "deleteTest": "Excluir Teste",
        "runTest": "Executar Teste",
        "runBatch": "Executar Lote",
        "schedule": "Agendar",
        "results": "Resultados",
        "metrics": "Métricas",
        "comparison": "Comparação",
        "baseline": "Baseline",
        "variant": "Variante",
        "winner": "Vencedor",
        "confidence": "Confiança",
        "significance": "Significância",
        "sampleSize": "Tamanho da Amostra",
        "iterations": "Iterações",
        "concurrency": "Concorrência",
        "rateLimit": "Limite de Taxa",
        "costEstimate": "Estimativa de Custo",
        "timeEstimate": "Estimativa de Tempo",
        "progress": "Progresso",
        "queue": "Fila",
        "logs": "Logs",
        "errors": "Erros",
        "warnings": "Avisos",
        "export": "Exportar Resultados",
        "share": "Compartilhar Resultados",
        "report": "Gerar Relatório"
    },
    
    # Layer 3 module
    "layer3": {
        "title": "Camada 3: Otimização e Implantação",
        "optimize": "Otimizar",
        "autoTune": "Ajuste Automático",
        "suggestions": "Sugestões",
        "improvements": "Melhorias",
        "performance": "Desempenho",
        "cost": "Custo",
        "quality": "Qualidade",
        "speed": "Velocidade",
        "accuracy": "Precisão",
        "tradeoffs": "Compromissos",
        "deploy": "Implantar",
        "version": "Versão",
        "changelog": "Registro de Alterações",
        "rollback": "Reverter",
        "monitor": "Monitorar",
        "alerts": "Alertas",
        "threshold": "Limite",
        "notification": "Notificação",
        "email": "Email",
        "webhook": "Webhook",
        "slack": "Slack",
        "dashboard": "Painel",
        "analytics": "Análises",
        "insights": "Insights",
        "trends": "Tendências",
        "forecasts": "Previsões",
        "recommendations": "Recomendações"
    },
    
    # Pipeline module
    "pipeline": {
        "title": "Fluxo de Trabalho Pipeline",
        "create": "Criar Pipeline",
        "edit": "Editar Pipeline",
        "delete": "Excluir Pipeline",
        "run": "Executar Pipeline",
        "stop": "Parar Pipeline",
        "pause": "Pausar",
        "resume": "Retomar",
        "status": "Status",
        "stages": "Estágios",
        "addStage": "Adicionar Estágio",
        "removeStage": "Remover Estágio",
        "configure": "Configurar",
        "dependencies": "Dependências",
        "parallel": "Paralelo",
        "sequential": "Sequencial",
        "conditional": "Condicional",
        "trigger": "Gatilho",
        "manual": "Manual",
        "scheduled": "Agendado",
        "automatic": "Automático",
        "webhook": "Webhook"
    },
    
    # WhyPromptly module
    "whyPromptly": {
        "title": "Por Que Escolher Promptly?",
        "subtitle": "A plataforma definitiva para otimização de prompts LLM",
        "reason1Title": "Economize Tempo",
        "reason1Desc": "Automatize testes e otimização de seus prompts",
        "reason2Title": "Reduza Custos",
        "reason2Desc": "Otimize o uso de tokens e reduza custos de API",
        "reason3Title": "Qualidade Melhorada",
        "reason3Desc": "Obtenha resultados consistentes e de alta qualidade",
        "reason4Title": "Insights Baseados em Dados",
        "reason4Desc": "Tome decisões informadas com métricas detalhadas",
        "reason5Title": "Fácil de Usar",
        "reason5Desc": "Interface intuitiva para todos os níveis de habilidade",
        "reason6Title": "Suporte Empresarial",
        "reason6Desc": "Suporte dedicado e recursos empresariais",
        "cta": "Comece Hoje",
        "testimonial1": "Promptly transformou nosso fluxo de trabalho LLM",
        "testimonial2": "Economia de custos incrível e muito melhor qualidade",
        "testimonial3": "Melhor ferramenta para desenvolvimento de prompts",
        "stats1": "10x mais rápido",
        "stats2": "50% de redução de custos",
        "stats3": "99.9% de tempo de atividade",
        "stats4": "Mais de 1000 usuários satisfeitos"
    }
}

# 印地语翻译映射
hi_translations = {
    # Common module
    "common": {
        "appName": "Promptly",
        "welcome": "स्वागत है",
        "loading": "लोड हो रहा है...",
        "error": "त्रुटि",
        "success": "सफलता",
        "cancel": "रद्द करें",
        "confirm": "पुष्टि करें",
        "save": "सहेजें",
        "delete": "हटाएं",
        "edit": "संपादित करें",
        "close": "बंद करें",
        "back": "पीछे",
        "next": "अगला",
        "submit": "सबमिट करें",
        "reset": "रीसेट करें",
        "search": "खोजें",
        "filter": "फ़िल्टर",
        "sort": "क्रमबद्ध करें",
        "export": "निर्यात करें",
        "import": "आयात करें",
        "download": "डाउनलोड करें",
        "upload": "अपलोड करें",
        "view": "देखें",
        "copy": "कॉपी करें",
        "paste": "पेस्ट करें",
        "cut": "कट करें",
        "selectAll": "सभी चुनें",
        "deselectAll": "सभी अचयनित करें",
        "refresh": "रिफ्रेश करें",
        "reload": "पुनः लोड करें",
        "retry": "पुनः प्रयास करें",
        "undo": "पूर्ववत करें",
        "redo": "फिर से करें",
        "help": "सहायता",
        "about": "के बारे में",
        "settings": "सेटिंग्स",
        "logout": "लॉग आउट",
        "login": "लॉग इन"
    },
    
    # Alerts module
    "alerts": {
        "success": "ऑपरेशन सफल रहा!",
        "error": "एक त्रुटि हुई",
        "warning": "चेतावनी",
        "info": "जानकारी",
        "confirmDelete": "क्या आप वाकई हटाना चाहते हैं?",
        "confirmAction": "क्या आप जारी रखना चाहते हैं?",
        "unsavedChanges": "आपके पास अनसेव किए गए परिवर्तन हैं",
        "saveSuccess": "सफलतापूर्वक सहेजा गया",
        "saveFailed": "सहेजने में विफल",
        "deleteSuccess": "सफलतापूर्वक हटाया गया",
        "deleteFailed": "हटाने में विफल",
        "updateSuccess": "सफलतापूर्वक अपडेट किया गया",
        "updateFailed": "अपडेट करने में विफल",
        "loadFailed": "डेटा लोड करने में विफल",
        "networkError": "नेटवर्क त्रुटि, कृपया अपना कनेक्शन जांचें",
        "invalidInput": "अमान्य इनपुट",
        "requiredField": "यह फ़ील्ड आवश्यक है",
        "invalidFormat": "अमान्य प्रारूप",
        "copySuccess": "क्लिपबोर्ड पर कॉपी किया गया",
        "copyFailed": "कॉपी करने में विफल"
    },
    
    # Hero module
    "hero": {
        "title": "Promptly के साथ अपने LLM Prompts को ऑप्टिमाइज़ करें",
        "subtitle": "AI-संचालित पेशेवर Prompt परीक्षण और ऑप्टिमाइज़ेशन प्लेटफ़ॉर्म",
        "description": "स्वचालित वर्कफ़्लो और पेशेवर मेट्रिक्स के साथ अपने LLM Prompts का परीक्षण, तुलना और ऑप्टिमाइज़ करें",
        "cta": "निःशुल्क शुरू करें",
        "learnMore": "और जानें",
        "watchDemo": "डेमो देखें",
        "feature1": "स्वचालित A/B परीक्षण",
        "feature2": "रीयल-टाइम मेट्रिक्स",
        "feature3": "मल्टी-मॉडल समर्थन",
        "feature4": "संस्करण प्रबंधन",
        "trustedBy": "द्वारा विश्वसनीय",
        "companies": "1000+ कंपनियां"
    },
    
    # Dynamic module
    "dynamic": {
        "bestPrompt": "सर्वश्रेष्ठ Prompt",
        "testCases": "परीक्षण मामले",
        "successRate": "सफलता दर",
        "avgTokens": "औसत Tokens",
        "avgLatency": "औसत विलंबता",
        "totalRuns": "कुल रन",
        "lastRun": "अंतिम रन",
        "status": "स्थिति",
        "running": "चल रहा है",
        "completed": "पूर्ण",
        "failed": "विफल",
        "pending": "लंबित",
        "cancelled": "रद्द",
        "noData": "कोई डेटा उपलब्ध नहीं",
        "loadingData": "डेटा लोड हो रहा है...",
        "refreshData": "डेटा रिफ्रेश करें",
        "autoRefresh": "स्वतः रिफ्रेश",
        "realtime": "रीयल-टाइम"
    },
    
    # Glossary module
    "glossary": {
        "title": "शब्दकोश",
        "prompt": "Prompt",
        "promptDesc": "भाषा मॉडल को दिया गया इनपुट निर्देश",
        "llm": "LLM (बड़ा भाषा मॉडल)",
        "llmDesc": "GPT, Claude आदि जैसे बड़े भाषा मॉडल",
        "token": "Token",
        "tokenDesc": "LLM द्वारा संसाधित टेक्स्ट की इकाई",
        "latency": "Latency",
        "latencyDesc": "मॉडल का प्रतिक्रिया समय",
        "temperature": "Temperature",
        "temperatureDesc": "आउटपुट की यादृच्छिकता को नियंत्रित करता है (0-2)",
        "maxTokens": "अधिकतम Tokens",
        "maxTokensDesc": "प्रतिक्रिया की अधिकतम लंबाई",
        "topP": "Top P",
        "topPDesc": "विविधता के लिए न्यूक्लियस सैंपलिंग",
        "frequencyPenalty": "Frequency Penalty",
        "frequencyPenaltyDesc": "शब्द दोहराव को कम करता है (-2 से 2)",
        "presencePenalty": "Presence Penalty",
        "presencePenaltyDesc": "नए विषयों को प्रोत्साहित करता है (-2 से 2)",
        "stopSequence": "Stop Sequence",
        "stopSequenceDesc": "विशिष्ट अनुक्रमों पर पीढ़ी को रोकता है",
        "systemPrompt": "System Prompt",
        "systemPromptDesc": "मॉडल के लिए संदर्भ निर्देश",
        "userPrompt": "User Prompt",
        "userPromptDesc": "उपयोगकर्ता की क्वेरी",
        "assistantPrompt": "Assistant Prompt",
        "assistantPromptDesc": "मॉडल की प्रतिक्रिया",
        "fewShot": "Few-Shot",
        "fewShotDesc": "कुछ उदाहरणों के साथ सीखना",
        "zeroShot": "Zero-Shot",
        "zeroShotDesc": "बिना उदाहरणों के सीखना",
        "chainOfThought": "Chain of Thought",
        "chainOfThoughtDesc": "चरण-दर-चरण तर्क",
        "embedding": "Embedding",
        "embeddingDesc": "टेक्स्ट का वेक्टर प्रतिनिधित्व",
        "vectorDB": "Vector Database",
        "vectorDBDesc": "शब्दार्थ खोज के लिए स्टोरेज",
        "rag": "RAG (पुनर्प्राप्ति संवर्धित पीढ़ी)",
        "ragDesc": "पुनर्प्राप्ति से संवर्धित पीढ़ी",
        "fineTuning": "Fine-Tuning",
        "fineTuningDesc": "विशिष्ट डेटा पर मॉडल प्रशिक्षण",
        "inference": "Inference",
        "inferenceDesc": "मॉडल द्वारा प्रतिक्रिया पीढ़ी"
    },
    
    # Test Cases module
    "testCases": {
        "title": "परीक्षण मामले",
        "create": "परीक्षण मामला बनाएं",
        "edit": "परीक्षण मामला संपादित करें",
        "delete": "परीक्षण मामला हटाएं",
        "run": "परीक्षण चलाएं",
        "runAll": "सभी चलाएं",
        "stopAll": "सभी रोकें",
        "name": "नाम",
        "description": "विवरण",
        "input": "इनपुट",
        "expectedOutput": "अपेक्षित आउटपुट",
        "actualOutput": "वास्तविक आउटपुट",
        "result": "परिणाम",
        "passed": "पास",
        "failed": "फेल",
        "skipped": "छोड़ा गया",
        "duration": "अवधि",
        "createdAt": "बनाया गया",
        "updatedAt": "अपडेट किया गया",
        "lastRun": "अंतिम रन",
        "runCount": "रन गणना",
        "successRate": "सफलता दर",
        "avgDuration": "औसत अवधि",
        "tags": "टैग",
        "priority": "प्राथमिकता",
        "high": "उच्च",
        "medium": "मध्यम",
        "low": "निम्न",
        "category": "श्रेणी",
        "functional": "कार्यात्मक",
        "performance": "प्रदर्शन",
        "security": "सुरक्षा",
        "usability": "उपयोगिता",
        "compatibility": "संगतता",
        "regression": "प्रतिगमन",
        "smoke": "स्मोक",
        "integration": "एकीकरण",
        "unit": "इकाई",
        "e2e": "एंड-टू-एंड"
    },
    
    # User Guide module
    "userGuide": {
        "title": "उपयोगकर्ता गाइड",
        "welcome": "Promptly में आपका स्वागत है",
        "gettingStarted": "शुरुआत करना",
        "quickStart": "त्वरित प्रारंभ",
        "tutorial": "ट्यूटोरियल",
        "documentation": "प्रलेखन",
        "faq": "अक्सर पूछे जाने वाले प्रश्न",
        "support": "समर्थन",
        "contact": "संपर्क करें",
        "feedback": "फीडबैक",
        "reportBug": "बग रिपोर्ट करें",
        "featureRequest": "फीचर अनुरोध",
        "step1": "चरण 1: एक प्रोजेक्ट बनाएं",
        "step1Desc": "अपने Prompts को व्यवस्थित करने के लिए एक नया प्रोजेक्ट बनाकर शुरू करें",
        "step2": "चरण 2: Prompts जोड़ें",
        "step2Desc": "अपने Prompts जोड़ें और पैरामीटर कॉन्फ़िगर करें",
        "step3": "चरण 3: परीक्षण चलाएं",
        "step3Desc": "अपने परीक्षण चलाएं और परिणामों का विश्लेषण करें",
        "step4": "चरण 4: ऑप्टिमाइज़ करें",
        "step4Desc": "अपने Prompts को ऑप्टिमाइज़ करने के लिए इनसाइट्स का उपयोग करें",
        "tips": "सुझाव",
        "tip1": "स्पष्ट और संक्षिप्त System Prompts का उपयोग करें",
        "tip2": "सर्वश्रेष्ठ खोजने के लिए कई वेरिएंट का परीक्षण करें",
        "tip3": "प्रदर्शन मेट्रिक्स की निगरानी करें",
        "tip4": "परिणामों के आधार पर पुनरावृत्ति करें",
        "bestPractices": "सर्वोत्तम प्रथाएं",
        "practice1": "स्पष्ट सफलता मानदंड परिभाषित करें",
        "practice2": "विविध परीक्षण मामलों का उपयोग करें",
        "practice3": "अपने Prompts को संस्करणित करें",
        "practice4": "अपने निर्णयों को प्रलेखित करें",
        "troubleshooting": "समस्या निवारण",
        "issue1": "मॉडल प्रतिक्रिया नहीं दे रहा",
        "solution1": "अपने API कनेक्शन और दर सीमाओं की जांच करें",
        "issue2": "असंगत परिणाम",
        "solution2": "Temperature समायोजित करें और अधिक संदर्भ जोड़ें",
        "issue3": "धीमी प्रतिक्रियाएं",
        "solution3": "Prompt लंबाई और अधिकतम Tokens को ऑप्टिमाइज़ करें"
    },
    
    # Layer 1 module
    "layer1": {
        "title": "लेयर 1: मूल कॉन्फ़िगरेशन",
        "model": "मॉडल",
        "selectModel": "मॉडल चुनें",
        "modelVersion": "मॉडल संस्करण",
        "apiKey": "API कुंजी",
        "apiEndpoint": "API एंडपॉइंट",
        "temperature": "Temperature",
        "maxTokens": "अधिकतम Tokens",
        "topP": "Top P",
        "frequencyPenalty": "Frequency Penalty",
        "presencePenalty": "Presence Penalty",
        "stopSequence": "Stop Sequence",
        "timeout": "टाइमआउट",
        "retries": "पुनः प्रयास",
        "systemPrompt": "System Prompt",
        "systemPromptPlaceholder": "अपना System Prompt दर्ज करें...",
        "advanced": "उन्नत सेटिंग्स",
        "basic": "मूल सेटिंग्स",
        "custom": "कस्टम कॉन्फ़िगरेशन",
        "preset": "प्रीसेट",
        "creative": "रचनात्मक",
        "balanced": "संतुलित",
        "precise": "सटीक",
        "save": "कॉन्फ़िगरेशन सहेजें",
        "load": "कॉन्फ़िगरेशन लोड करें",
        "reset": "डिफ़ॉल्ट पर रीसेट करें",
        "validate": "कॉन्फ़िगरेशन मान्य करें",
        "test": "कॉन्फ़िगरेशन परीक्षण करें"
    },
    
    # Layer 2 module
    "layer2": {
        "title": "लेयर 2: परीक्षण और मूल्यांकन",
        "testSuite": "परीक्षण सूट",
        "createTest": "परीक्षण बनाएं",
        "editTest": "परीक्षण संपादित करें",
        "deleteTest": "परीक्षण हटाएं",
        "runTest": "परीक्षण चलाएं",
        "runBatch": "बैच चलाएं",
        "schedule": "अनुसूची",
        "results": "परिणाम",
        "metrics": "मेट्रिक्स",
        "comparison": "तुलना",
        "baseline": "बेसलाइन",
        "variant": "वेरिएंट",
        "winner": "विजेता",
        "confidence": "विश्वास",
        "significance": "महत्व",
        "sampleSize": "नमूना आकार",
        "iterations": "पुनरावृत्ति",
        "concurrency": "समवर्तीता",
        "rateLimit": "दर सीमा",
        "costEstimate": "लागत अनुमान",
        "timeEstimate": "समय अनुमान",
        "progress": "प्रगति",
        "queue": "कतार",
        "logs": "लॉग",
        "errors": "त्रुटियां",
        "warnings": "चेतावनियां",
        "export": "परिणाम निर्यात करें",
        "share": "परिणाम साझा करें",
        "report": "रिपोर्ट जनरेट करें"
    },
    
    # Layer 3 module
    "layer3": {
        "title": "लेयर 3: ऑप्टिमाइज़ेशन और डिप्लॉयमेंट",
        "optimize": "ऑप्टिमाइज़ करें",
        "autoTune": "ऑटो-ट्यून",
        "suggestions": "सुझाव",
        "improvements": "सुधार",
        "performance": "प्रदर्शन",
        "cost": "लागत",
        "quality": "गुणवत्ता",
        "speed": "गति",
        "accuracy": "सटीकता",
        "tradeoffs": "ट्रेडऑफ",
        "deploy": "डिप्लॉय करें",
        "version": "संस्करण",
        "changelog": "परिवर्तन लॉग",
        "rollback": "रोलबैक",
        "monitor": "निगरानी करें",
        "alerts": "अलर्ट",
        "threshold": "सीमा",
        "notification": "सूचना",
        "email": "ईमेल",
        "webhook": "Webhook",
        "slack": "Slack",
        "dashboard": "डैशबोर्ड",
        "analytics": "एनालिटिक्स",
        "insights": "इनसाइट्स",
        "trends": "ट्रेंड",
        "forecasts": "पूर्वानुमान",
        "recommendations": "सिफारिशें"
    },
    
    # Pipeline module
    "pipeline": {
        "title": "Pipeline वर्कफ़्लो",
        "create": "Pipeline बनाएं",
        "edit": "Pipeline संपादित करें",
        "delete": "Pipeline हटाएं",
        "run": "Pipeline चलाएं",
        "stop": "Pipeline रोकें",
        "pause": "रोकें",
        "resume": "फिर से शुरू करें",
        "status": "स्थिति",
        "stages": "चरण",
        "addStage": "चरण जोड़ें",
        "removeStage": "चरण हटाएं",
        "configure": "कॉन्फ़िगर करें",
        "dependencies": "निर्भरताएं",
        "parallel": "समानांतर",
        "sequential": "क्रमिक",
        "conditional": "सशर्त",
        "trigger": "ट्रिगर",
        "manual": "मैनुअल",
        "scheduled": "अनुसूचित",
        "automatic": "स्वचालित",
        "webhook": "Webhook"
    },
    
    # WhyPromptly module
    "whyPromptly": {
        "title": "Promptly क्यों चुनें?",
        "subtitle": "LLM Prompt ऑप्टिमाइज़ेशन के लिए अंतिम प्लेटफ़ॉर्म",
        "reason1Title": "समय बचाएं",
        "reason1Desc": "अपने Prompts के परीक्षण और ऑप्टिमाइज़ेशन को स्वचालित करें",
        "reason2Title": "लागत कम करें",
        "reason2Desc": "Token उपयोग को ऑप्टिमाइज़ करें और API लागत कम करें",
        "reason3Title": "बेहतर गुणवत्ता",
        "reason3Desc": "सुसंगत और उच्च गुणवत्ता वाले परिणाम प्राप्त करें",
        "reason4Title": "डेटा-संचालित इनसाइट्स",
        "reason4Desc": "विस्तृत मेट्रिक्स के साथ सूचित निर्णय लें",
        "reason5Title": "उपयोग में आसान",
        "reason5Desc": "सभी कौशल स्तरों के लिए सहज इंटरफ़ेस",
        "reason6Title": "एंटरप्राइज़ समर्थन",
        "reason6Desc": "समर्पित समर्थन और एंटरप्राइज़ सुविधाएं",
        "cta": "आज शुरू करें",
        "testimonial1": "Promptly ने हमारे LLM वर्कफ़्लो को बदल दिया",
        "testimonial2": "अद्भुत लागत बचत और बहुत बेहतर गुणवत्ता",
        "testimonial3": "Prompt विकास के लिए सर्वश्रेष्ठ उपकरण",
        "stats1": "10x तेज़",
        "stats2": "50% लागत कमी",
        "stats3": "99.9% अपटाइम",
        "stats4": "1000+ संतुष्ट उपयोगकर्ता"
    }
}

# 函数：合并翻译
def merge_translations(base, updates):
    result = base.copy() if isinstance(base, dict) else {}
    for key, value in updates.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = merge_translations(result[key], value)
        else:
            result[key] = value
    return result

# 处理所有4种语言
languages = [
    ('ar', ar_translations, 'العربية'),
    ('ko', ko_translations, '한국어'),
    ('pt', pt_translations, 'Português'),
    ('hi', hi_translations, 'हिन्दी')
]

for lang_code, translations, lang_name in languages:
    # 读取现有翻译
    with open(f'frontend/locales/{lang_code}.json', 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    # 合并翻译
    complete = merge_translations(existing, translations)
    
    # 写入更新后的文件
    with open(f'frontend/locales/{lang_code}.json', 'w', encoding='utf-8') as f:
        json.dump(complete, f, ensure_ascii=False, indent=2)
    
    print(f"✅ {lang_name} ({lang_code}) 翻译完成！")

print("\n" + "=" * 60)
print("🎉 所有4种语言翻译完成！")
print("📊 已完成的语言: 阿拉伯语、韩语、葡萄牙语、印地语")
print("=" * 60)



